version: '3'
services:
  container_a:
    build:
      context: ./A
      dockerfile: Dockerfile
    container_name: my_container_a  # Custom container name
    ports:
      - "8000:8000"
    volumes:
      - ./A:/app
    # Other configuration for container A

  # container_b:
  #     build:
  #       context: ./B
  #       dockerfile: Dockerfile
  #     container_name: my_container_b  # Custom container name
  #     ports:
  #       - "5000:5000"
  #     volumes:
  #       - ./B:/app
  #     # Other configuration for container B

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
